---
title: "simulation"
author: "Stephen Yuan"
date: "11/19/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

set.seed(1)
```

## Lets simulate something..

I have functions

```{r}
sim_mean_sd = function(sample_size, mu = 3, sigma = 4) {
  
  sim_data = 
  tibble(
    x = rnorm(n = sample_size, mean = mu, sd = sigma)
  )

  sim_data %>% 
    summarise(
      mean = mean(x),
      sd = sd(x)
    )

}
```

I can "simulate" by running this line.

```{r}
sim_mean_sd(30)
```

## Lets simulate a lot

Lets start a `for` loop

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(sample_size = 30)
  
}

bind_rows(output)
```

Lets use a loop function.

```{r}
?rerun()

sim_results = 
  rerun(5000, sim_mean_sd(sample_size = 30)) %>% 
  bind_rows()
```

Lets look at results .. 

```{r}
sim_results %>% 
  ggplot(aes(x = mean)) + geom_density()

sim_results %>% 
  summarise(
    avg_samp_mean = mean(mean),
    sd_samp_mean = sd(mean)
  )

sim_results %>% 
  ggplot(aes(x = sd)) +geom_density()
```

## Lets try other sample sizes

```{r}
n_list = 
  list(
    "n = 30" = 30,
    "n = 60" = 60,
    "n = 120" = 120,
    "n = 240" = 240
  )

output = vector("list", length = 4)

output[[1]] = 
  rerun(100, sim_mean_sd(sample_size = n_list[[1]])) %>% 
  bind_rows()

for (i in 1:4) {
  
  output[[i]] = 
    rerun(100, sim_mean_sd(sample_size = n_list[[i]])) %>% 
    bind_rows()
  
}

output[[4]]
```

```{r, cache = TRUE}
sim_results = 
  tibble(
    sample_size = c(30, 60, 120, 240)
  ) %>% 
  mutate(
    output_list = map(.x = sample_size, ~ rerun(10, sim_mean_sd(.x))),
    estimate_df = map(output_list, bind_rows)
    ) %>% 
    select(-output_list) %>% 
    unnest(estimate_df)
```

Do some data frame things.

```{r}
sim_results %>% 
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mean)) +
  geom_boxplot()
```

Do some data frame things.

```{r}
sim_results %>% 
  group_by(sample_size) %>% 
  summarise(
    avg_samp_mean = mean(mean),
    sd_samp_mean = sd(mean)
  ) 
```


