---
title: "writing_functions"
author: "Stephen Yuan"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```

## do something simple: Z-score

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute z-score

```{r}
z_scores = function(x) {
  
  if(!(is.numeric(x))) {
    stop("Input must be numeric")
  }
  
  if(length(x) < 3) {
    stop("Input must have at least three numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(x_vec)
```

Try my function on some other things.

```{r, error=TRUE}
z_scores(3)
z_scores("wechat")
z_scores(mtcars)
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

## Multiple outputs

```{r}
mean_and_sd = function(x) {
  
  if(!(is.numeric(x))) {
    stop("Input must be numeric")
  }
  
  if(length(x) < 3) {
    stop("Input must have at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

check that the function works.

```{r}
x_vec = rnorm(100, mean = 3, sd = 4)
mean_and_sd(x_vec)
```

## Multiple inputs

Try to do the following into a function:
```{r}
sim_data = 
  tibble(
    x = rnorm(100, mean = 4, sd = 3)
  )

sim_data %>% 
  summarise(
    mean = mean(x),
    sd = sd(x)
  )
```

```{r}
sim_mean_sd = function(sample_size, mu = 3, sigma = 4) {
  
  sim_data = 
  tibble(
    x = rnorm(n = sample_size, mean = mu, sd = sigma)
  )

sim_data %>% 
  summarise(
    mean = mean(x),
    sd = sd(x)
  )
}

sim_mean_sd(100, 6, 5) #argument:实参
sim_mean_sd(100)
```


## Lets review Napoleon Dynamite

```{r, eval=FALSE}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

what about the next page of reviews .. 

Lets turn that code into a function

```{r}
read_page_reviews = function(url) {
  
    dynamite_html = read_html(url)
    
    review_titles = 
      dynamite_html %>%
      html_nodes(".a-text-bold span") %>%
      html_text()
    
    review_stars = 
      dynamite_html %>%
      html_nodes("#cm_cr-review_list .review-rating") %>%
      html_text() %>%
      str_extract("^\\d") %>%
      as.numeric()
    
    review_text = 
      dynamite_html %>%
      html_nodes(".review-text-content span") %>%
      html_text() %>% 
      str_replace_all("\n", "") %>% 
      str_trim()
    
    reviews = tibble(
      title = review_titles,
      stars = review_stars,
      text = review_text
    )
    
    reviews # object that is gonna be returned
}
```

Try the function ..

```{r}
dynamite_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=2"

read_page_reviews(dynamite_url)
```

```{r}
dynamite_url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

dynamite_urls = str_c(dynamite_url_base, 1:5)

dynamite_urls[2]
```



