---
title: "Data Visualization 2"
author: "Stephen Yuan"
date: "10/4/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(viridisLite)
library(viridis)
library(ggthemes)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.height = "90%"
)
```

## Load the weather 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10, # 最低温
    tmax = tmax / 10) %>% # 最高温
  select(name, id, everything())
```

## Recall

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
```

## Labels

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperatures in 2017."
  )
```

## Scales

Start with the same plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temp (C)",
    y = "Max daily temp (C)",
    caption = "Data from rnoaa package; temp in 2017"
  ) +
# scales on x-axis
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0 C", "15 C")
  ) +
  scale_y_continuous(
    position = "right"
  ) +
  scale_y_continuous(
    trans = "sqrt"
  ) +
  scale_color_hue(
    h = c(100, 200)
  )
```

Look at color scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temp (C)",
    y = "Max daily temp (C)",
    caption = "Data from rnoaa package; temp in 2017"
  ) +
  scale_color_hue(
    name = "location",
    h = c(100, 300)
  ) +
   viridis::scale_color_viridis(
   name = "Location",
   discrete = TRUE
  )
```

## Themes

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temp (C)",
    y = "Max daily temp (C)",
    caption = "Data from rnoaa package; temp in 2017"
  ) +
  viridis::scale_color_viridis(
  name = "Location",
  discrete = TRUE
  ) +
  theme(legend.position = "bottom") 
# + theme_bw() 这么写会改回去
```

Change the overall theme.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temp (C)",
    y = "Max daily temp (C)",
    caption = "Data from rnoaa package; temp in 2017"
  ) +
  viridis::scale_color_viridis(
  name = "Location",
  discrete = TRUE
  ) +
  theme_minimal() +
  theme_excel()
```

Setting options

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d()
```

## `data` args in `geom`

```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

waikiki %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)
```

## `patchwork`

Faceting

```{r}
gg_tmax_tmin = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3)

ggp_prcp_dens = 
  weather_df %>% 
  filter(prcp > 100) %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .5) +
  theme(legend = none)

ggp_tmax_date = 
  weather_df %>% 
  ggplot(aws(x = data, y = tmax, color = name)) +
  geom_point() +
  geom_smooth() +
  facet_grid(. ~ name)

(gg_tmax_tmin + ggp_prcp_dens) / ggp_tmax_date
# (gg_tmax_tmin / ggp_prcp_dens) + ggp_tmax_date
```

## data manipulation: factors

```{r}
weather_df %>% 
  mutate(
    name = fct_reorder(name, tmax)
  ) %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

what about tmin and tmax ... ???

```{r}
weather_df %>% 
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to = "temperature"
  ) %>% 
  ggplot(aes(x = temperature, fill = observation)) +
  geom_density(alpha = .3) +
  facet_grid(. ~ name) 
```

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score"
  ) %>% 
  mutate(
    visit = recode(visit, "bl" = "00m")
  )

pulse_df %>% 
  ggplot(aes(x = visit, y = bdi)) +
  geom_boxplot()

pulse_df %>% 
  ggplot(aes(x = visit, y = bdi)) +
  geom_point() +
  ggeom_line(aes(group = id,))
```











